# Generated by Django 5.2.6 on 2025-09-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение для вопроса.', null=True, upload_to='questions/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.PositiveIntegerField(default=1, help_text='Укажите номер вопроса (от 1 до 9), который соответствует его номеру на карте.', unique=True, verbose_name='Номер вопроса'),
        ),
    ]
