# Generated by Django 5.2.6 on 2025-10-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_question_image_question_question_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_title', models.CharField(default='Праздники без опасности: забота о питомцах', max_length=255, verbose_name='Промо / Заголовок')),
                ('promo_description', models.TextField(default='Полезные советы о том, как уберечь животных от праздничных опасностей и сделать праздник комфортным для всех', verbose_name='Промо / Описание')),
                ('footer_title', models.CharField(default='Фонд защиты городских животных', max_length=255, verbose_name='Подвал / Заголовок')),
                ('footer_description', models.TextField(default='Защищаем права и интересы городских животных. Тех москвичей, которые сами о себе позаботиться не могут — кошек, собак, птиц и других животных нашего города', verbose_name='Подвал / Описание')),
            ],
            options={
                'verbose_name': 'Настройки контента сайта',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.PositiveIntegerField(help_text='Укажите номер вопроса (от 1 до 9), который соответствует его номеру на карте.', unique=True, verbose_name='Номер вопроса'),
        ),
    ]
