# Generated by Django 5.2.6 on 2025-10-01 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_sitecontent_alter_question_question_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('score', models.PositiveIntegerField(verbose_name='Правильных ответов')),
                ('total_questions', models.PositiveIntegerField(verbose_name='Всего вопросов')),
            ],
            options={
                'verbose_name': 'Попытка прохождения теста',
                'verbose_name_plural': 'Попытки прохождения тестов',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='promo_title',
            field=models.CharField(default='Праздники без&nbsp;опасности: забота о питомцах', max_length=255, verbose_name='Промо / Заголовок'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Ответ верный')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='content.quizattempt', verbose_name='Попытка')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.question', verbose_name='Вопрос')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.choice', verbose_name='Выбранный ответ')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
    ]
