# Generated by Django 5.2.6 on 2025-10-01 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_result_background_image_desktop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, help_text='Загрузите изображение для вопроса. Поддерживаются: svg, jpg, png.', null=True, upload_to='questions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'jpg', 'jpeg', 'png'])], verbose_name='Изображение'),
        ),
    ]
